name: Java GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar Java 21 manualmente
        run: sudo apt-get update && sudo apt-get install openjdk-21-jdk
      
      - name: Configurar JAVA_HOME manualmente
        run: export JAVA_HOME=/usr/lib/jvm/java-21-openjdk && echo $JAVA_HOME

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.0.2'
          cache: 'maven'

      - name: Install Maven
        run: mvn -version

      - name: Check Java version in GitHub Actions
        run: |
          echo "JAVA_HOME is: $JAVA_HOME"
          java -version
          javac -version

  code-quality:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PMD static analysis
        run: mvn pmd:pmd
        
      - name: Run Spotless format check
        run: mvn spotless:check

      - name: Fix problems with Spotless
        run: mvn spotless:apply

      - name: Execute test
        run: mvn test

  build:
    environment: secrets
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Creating Docker file
        run: docker build . -t manuelmedinap1/tareacicd:latest
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - run: docker push manuelmedinap1/tareacicd:latest

  deploy:
    environment: secrets
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploying project
        run: curl https://api.render.com/deploy/srv-cvqqnije5dus7380nar0?key=L2QrHLV1vBA
